[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "serve -s build"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 